FROM ubuntu:18.04

WORKDIR /usr/src/app/

RUN apt-get update -y && apt-get upgrade -y && apt-get install -y \
    vim \
    python3 \
    python3-pip


COPY ./requirements.txt ./

RUN pip3 install -r requirements.txt

COPY . ./
 
# Add crontab file in the cron directory
ADD crontab /etc/cron.d/mix-coins.cron
 
# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/mix-coins.cron
 
# Create the log file to be able to run tail
RUN touch /var/log/cron.log
 
# Run the command on container startup
CMD cron && tail -f /var/log/cron.log
