#!/usr/bin/env python3

import argparse
import sys
from jobcoin.cli import main

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--targets', nargs='+', help='The accounts that the jobCoins should be sent to')
    parser.add_argument('--branching', type=int, default=5, help='The number of addresses that the jobCoins should be sent to')
    parser.add_argument('--duration', type=int, default=69, help='How long should I take to transfer the jobcoins?')
    args = parser.parse_args()

    print('Welcome to the Jobcoin mixer!\n')
    print('Generating new addresses')
    addrs = main(args.targets, args.branching, args.duration)
    print('You may now send Jobcoins to address {}'.format(addrs['mix_addrs']['src']))
    print('They will be mixed and sent to your destination addresses.')

    
