#!/usr/bin/env python

import argparse
import sys
from jobcoin.cli import main

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--targets', nargs='+', help='The accounts that the jobCoins should be sent to')
    parser.add_argument('--branching', type=int, default=5, help='The number of addresses that the jobCoins should be sent to')
    parser.add_argument('--duration', type=int, default=3600, help='How long should I take to transfer the jobcoins?')
    args = parser.parse_args()
    print(args.targets)

    #sys.exit(main(args.targets, args.branching, args.duration))
    
